# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import faiss_pb2 as faiss__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FaissServiceStub(object):
  """message RemoveVectorByIdRequest {
  uint64 id = 1;
  uint64 vector_id = 2;
  }

  message RemoveVectorByIdResponse {

  }

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Heartbeat = channel.unary_unary(
        '/faiss.FaissService/Heartbeat',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=faiss__pb2.HeartbeatResponse.FromString,
        )
    self.Search = channel.unary_unary(
        '/faiss.FaissService/Search',
        request_serializer=faiss__pb2.SearchRequest.SerializeToString,
        response_deserializer=faiss__pb2.SearchResponse.FromString,
        )
    self.SearchById = channel.unary_unary(
        '/faiss.FaissService/SearchById',
        request_serializer=faiss__pb2.SearchByIdRequest.SerializeToString,
        response_deserializer=faiss__pb2.SearchByIdResponse.FromString,
        )
    self.AddVector = channel.unary_unary(
        '/faiss.FaissService/AddVector',
        request_serializer=faiss__pb2.AddVectorRequest.SerializeToString,
        response_deserializer=faiss__pb2.AddVectorResponse.FromString,
        )


class FaissServiceServicer(object):
  """message RemoveVectorByIdRequest {
  uint64 id = 1;
  uint64 vector_id = 2;
  }

  message RemoveVectorByIdResponse {

  }

  """

  def Heartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SearchById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddVector(self, request, context):
    """rpc RemoveVectorByIdRequest (RemoveVectorByIdRequest) returns (RemoveVectorByIdResponse);
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FaissServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Heartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.Heartbeat,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=faiss__pb2.HeartbeatResponse.SerializeToString,
      ),
      'Search': grpc.unary_unary_rpc_method_handler(
          servicer.Search,
          request_deserializer=faiss__pb2.SearchRequest.FromString,
          response_serializer=faiss__pb2.SearchResponse.SerializeToString,
      ),
      'SearchById': grpc.unary_unary_rpc_method_handler(
          servicer.SearchById,
          request_deserializer=faiss__pb2.SearchByIdRequest.FromString,
          response_serializer=faiss__pb2.SearchByIdResponse.SerializeToString,
      ),
      'AddVector': grpc.unary_unary_rpc_method_handler(
          servicer.AddVector,
          request_deserializer=faiss__pb2.AddVectorRequest.FromString,
          response_serializer=faiss__pb2.AddVectorResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'faiss.FaissService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
